--- 
apiVersion: v1
data:
  client-id: <Your Clinet/ApplicationID of Azure app>
  client-secret: <Your Base64 Client Secret>
kind: Secret
metadata:
  name: argo-workflows-sso
  namespace: argo
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  sso: |
    insecureSkipVerify: true
    issuer: https://22.222.222.222/api/dex
    clientId:
      name: argo-workflows-sso
      key: client-id
    clientSecret:
      name: argo-workflows-sso
      key: client-secret
    redirectUrl: https://11.111.11.111:2746/oauth2/callback